name: Simplified Continuous Integration

on: [pull_request]

jobs:
  build:
    name: Build on Ubuntu with ${{ matrix.package_manager }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x]
        package_manager: ['npm', 'pnpm']
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install pnpm
        if: matrix.package_manager == 'pnpm'
        run: npm install -g pnpm

      - name: Install dependencies
        run: ${{ matrix.package_manager }} install

      - name: Run build
        run: ${{ matrix.package_manager }} build

  test:
    name: Test on Ubuntu with ${{ matrix.package_manager }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x]
        package_manager: ['npm', 'pnpm']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install pnpm
        if: matrix.package_manager == 'pnpm'
        run: npm install -g pnpm

      - name: Install dependencies
        run: ${{ matrix.package_manager }} install

      - name: Run tests
        run: ${{ matrix.package_manager }} test
